import type {
    DesignColorToken,
    DesignIntelligenceMetadata,
} from "@/lib/design-intelligence";

type DtfCreativeCatalogEntry = {
    name: string;
    description: string;
    sort_order: number;
    metadata: DesignIntelligenceMetadata;
};

type DtfPaletteCatalogEntry = DtfCreativeCatalogEntry & {
    colors: DesignColorToken[];
};

export const DTF_STYLE_PROMPT_OVERRIDES: Record<string, string> = {
    "ملصق (Sticker)": "die-cut sticker style, vector art, flat colors, bold outlines",
    "أنمي/مانغا (Anime/Manga)": "anime style, manga illustration, Japanese animation art, vivid",
    "بوب آرت (Pop Art)": "pop art, Andy Warhol style, halftone dots, bold colors",
    "جرافيتي (Graffiti)": "street art, graffiti style, spray paint, urban, edgy",
    "فن الخطوط (Line Art)": "continuous line art, minimalist line drawing, focused on form",
    "هندسي (Geometric)": "geometric patterns, mathematical shapes, symmetric, structural",
    "بكسل آرت (Pixel Art)": "pixel art, 8-bit, 16-bit, retro gaming style, sharp edges",
    "فينتيج (Vintage)": "vintage aesthetic, retro design, slightly distressed, classic",
    "سايبر بانك (Cyberpunk)": "cyberpunk, futuristic, sci-fi, high tech, urban dystopia",
    "بسيط (Minimalist)": "minimalist design, clean lines, simple forms, negative space",
    "ثلاثي الأبعاد (3D)": "3d render, octane render, c4d, plastic, depth, professional",
};

export const DTF_TECHNIQUE_PROMPT_OVERRIDES: Record<string, string> = {
    "رسم رقمي (Digital)": "digital illustration, crisp digital art",
    "ألوان مائية (Watercolor)": "watercolor painting, fluid, color bleeds, artisanal",
    "ألوان زيتية (Oil)": "thick oil painting, impasto, visible brush strokes, fine art",
    "رسم بالقلم (Pen)": "pen and ink drawing, hatched lines, detailed sketching",
    "ايربراش (Airbrush)": "airbrush art, smooth gradients, soft edges, glossy",
    "حبر (Ink)": "black ink wash, sumi-e style, high contrast, elegant strokes",
    "طباعة ريزوغراف (Risograph)": "risograph print style, textured, vibrant overprinting, grainy",
};

export const DTF_PALETTE_PROMPT_OVERRIDES: Record<string, string> = {
    "تلقائي (Auto)": "best-matching colors for the theme",
    "نيون ساطع (Neon)": "vibrant neon colors, cyan, magenta, lime, glowing",
    "باستيل هادئ (Pastel)": "soft pastel colors, light pink, baby blue, mint green, serene",
    "أحادي اللون (Monochrome)": "monochrome, black and white, grayscale, varying shades",
    "ألوان ترابية (Earth)": "earth tones, brown, terracotta, olive green, warm beige, natural",
    "ريترو 80s (Retro)": "80s retro wave colors, hot pink, orange, purple, nostalgic",
    "فيبورويف (Vaporwave)": "vaporwave palette, turquoise, hot pink, soft purple, sunset yellow",
};

export const DTF_STUDIO_STYLE_CATALOG: DtfCreativeCatalogEntry[] = [
    {
        name: "ملصق (Sticker)",
        description: "تصميم قصاصات جريء بحدود واضحة ومساحات لونية حادة، مناسب للرسومات الأيقونية وقطع الشارع.",
        sort_order: 10,
        metadata: {
            creative_direction: "die-cut graphic sticker",
            energy: "high",
            complexity: "balanced",
            luxury_tier: "core",
            story_hook: "قطعة تبدو كملصق فاخر مطبوع بدقة عالية",
            keywords: ["sticker", "vector", "bold", "outline"],
            moods: ["جريء", "مرح", "واضح"],
            audiences: ["streetwear", "drops", "daily luxury"],
            placements: ["chest", "back"],
            recommended_methods: ["from_text", "from_image", "studio"],
            notes: "أفضل خيار للرسومات الصريحة والشعارات البصرية والملامح الواضحة.",
        },
    },
    {
        name: "أنمي/مانغا (Anime/Manga)",
        description: "جمالية يابانية نابضة، تعبيرات قوية وتباين بصري مناسب للشخصيات والقصص.",
        sort_order: 20,
        metadata: {
            creative_direction: "anime illustration energy",
            energy: "high",
            complexity: "bold",
            luxury_tier: "signature",
            story_hook: "لوحة أنمي محسوبة كأنها لقطة افتتاحية من مانغا فاخرة",
            keywords: ["anime", "manga", "character", "dynamic"],
            moods: ["حماسي", "حي", "قوي"],
            audiences: ["anime fans", "drops", "youth"],
            placements: ["chest", "back"],
            recommended_methods: ["from_text", "from_image", "studio"],
            notes: "مناسب للشخصيات والوجوه واللقطات الحركية والموضوعات الخيالية.",
        },
    },
    {
        name: "بوب آرت (Pop Art)",
        description: "ألوان صادمة، تباين قوي وإيقاع بصري واضح مستلهم من ملصقات الثقافة الجماهيرية.",
        sort_order: 30,
        metadata: {
            creative_direction: "bold pop art statement",
            energy: "high",
            complexity: "balanced",
            luxury_tier: "core",
            story_hook: "قطعة تلفت النظر من أول لمحة من خلال اللون والضربة الجريئة",
            keywords: ["pop art", "halftone", "statement", "bold"],
            moods: ["مشع", "صاخب", "مرِح"],
            audiences: ["drops", "giftable", "streetwear"],
            placements: ["chest", "back"],
            recommended_methods: ["from_text", "from_image", "studio"],
            notes: "يمتاز بالحضور الفوري وبناء التكوين حول عناصر قليلة لكنها بارزة.",
        },
    },
    {
        name: "جرافيتي (Graffiti)",
        description: "ستايل شارع خام، حروف وأشكال مرشوشة ومشحونة بطاقة حضرية مباشرة.",
        sort_order: 40,
        metadata: {
            creative_direction: "urban graffiti attitude",
            energy: "high",
            complexity: "bold",
            luxury_tier: "core",
            story_hook: "قطعة بروح الجدار والشارع والهوية الجريئة غير الملمعة",
            keywords: ["graffiti", "street", "spray", "urban"],
            moods: ["متمرد", "خام", "شبابي"],
            audiences: ["streetwear", "drops", "urban culture"],
            placements: ["chest", "back"],
            recommended_methods: ["from_text", "from_image", "studio"],
            notes: "ممتاز للهوية الشبابية والرسائل الجريئة والأشكال الحرة.",
        },
    },
    {
        name: "فن الخطوط (Line Art)",
        description: "تجريد نظيف يعتمد على الخط والتكوين أكثر من الكتلة اللونية، مناسب للقطع الراقية الهادئة.",
        sort_order: 50,
        metadata: {
            creative_direction: "minimal linework elegance",
            energy: "low",
            complexity: "minimal",
            luxury_tier: "signature",
            story_hook: "فخامة ناعمة مبنية على الخط والفراغ لا على ازدحام التفاصيل",
            keywords: ["line art", "minimal", "contour", "clean"],
            moods: ["هادئ", "راقي", "متزن"],
            audiences: ["daily luxury", "minimal lovers", "gifts"],
            placements: ["chest", "shoulder_right", "shoulder_left"],
            recommended_methods: ["from_text", "from_image", "studio"],
            notes: "أفضل للرسومات الدقيقة والتكوينات البسيطة والقصائد البصرية الهادئة.",
        },
    },
    {
        name: "هندسي (Geometric)",
        description: "تنسيق مبني على الأشكال والزوايا والبنية الرياضية، يعطي إحساسًا هندسيًا محسوبًا ونظيفًا.",
        sort_order: 60,
        metadata: {
            creative_direction: "structured geometric composition",
            energy: "medium",
            complexity: "balanced",
            luxury_tier: "signature",
            story_hook: "قطعة تبدو مصممة بمنطق معماري متوازن ودقيق",
            keywords: ["geometric", "structured", "symmetry", "shapes"],
            moods: ["متوازن", "دقيق", "تقني"],
            audiences: ["design lovers", "editorial", "minimal tech"],
            placements: ["chest", "back"],
            recommended_methods: ["from_text", "from_image", "studio"],
            notes: "مناسب للشعارات البصرية والتجريدات المنظمة والأفكار ذات البناء القوي.",
        },
    },
    {
        name: "بكسل آرت (Pixel Art)",
        description: "روح ألعاب كلاسيكية بدقة مربعة واضحة، تمنح القطعة شخصية مرحة ونوستالجية.",
        sort_order: 70,
        metadata: {
            creative_direction: "retro pixel nostalgia",
            energy: "medium",
            complexity: "balanced",
            luxury_tier: "core",
            story_hook: "قطعة تبدو كإحياء أنيق لذاكرة الألعاب القديمة",
            keywords: ["pixel art", "8-bit", "retro game", "nostalgia"],
            moods: ["مرِح", "نوستالجي", "خفيف"],
            audiences: ["gamers", "drops", "gifts"],
            placements: ["chest", "back"],
            recommended_methods: ["from_text", "from_image", "studio"],
            notes: "يفضل للرسومات الأيقونية والموضوعات المرحة ذات التكوين الشبكي.",
        },
    },
    {
        name: "فينتيج (Vintage)",
        description: "لمسة رجعية ناعمة مع إحساس مستهلك قليلًا وطبقات شخصية أكثر دفئًا من الحداثة المباشرة.",
        sort_order: 80,
        metadata: {
            creative_direction: "aged vintage print feeling",
            energy: "medium",
            complexity: "balanced",
            luxury_tier: "signature",
            story_hook: "قطعة تبدو كإصدار نادر محفوظ من زمن جميل",
            keywords: ["vintage", "retro", "aged", "heritage"],
            moods: ["حنين", "دافئ", "أصيل"],
            audiences: ["heritage lovers", "daily luxury", "gifts"],
            placements: ["chest", "back"],
            recommended_methods: ["from_text", "from_image", "studio"],
            notes: "يميل إلى الألوان الهادئة والملمس البصري غير الحاد.",
        },
    },
    {
        name: "سايبر بانك (Cyberpunk)",
        description: "رؤية مستقبلية مفعمة بالضوء والتقنية والتباين الحضري، مثالية للتصاميم اللافتة.",
        sort_order: 90,
        metadata: {
            creative_direction: "neon cyber future",
            energy: "high",
            complexity: "bold",
            luxury_tier: "editorial",
            story_hook: "قطعة تحمل وهج المدينة المستقبلية وتوترها البصري",
            keywords: ["cyberpunk", "future", "neon", "sci-fi"],
            moods: ["مستقبلي", "حاد", "داكن"],
            audiences: ["editorial", "drops", "sci-fi fans"],
            placements: ["chest", "back"],
            recommended_methods: ["from_text", "from_image", "studio"],
            notes: "يعمل بشكل أفضل مع النيون والتباينات العميقة والقصص التقنية.",
        },
    },
    {
        name: "بسيط (Minimalist)",
        description: "أقل عناصر ممكنة، حضور أنيق وصامت، مناسب للقطع اليومية الراقية.",
        sort_order: 100,
        metadata: {
            creative_direction: "quiet minimalist luxury",
            energy: "low",
            complexity: "minimal",
            luxury_tier: "signature",
            story_hook: "قطعة تبدو فاخرة لأنها لم تقل كل شيء دفعة واحدة",
            keywords: ["minimalist", "clean", "quiet luxury", "negative space"],
            moods: ["هادئ", "فخم", "صافي"],
            audiences: ["daily luxury", "minimalists", "premium basics"],
            placements: ["chest", "shoulder_right", "shoulder_left"],
            recommended_methods: ["from_text", "from_image", "studio"],
            notes: "ممتاز للنصوص المقتضبة والرموز الصغيرة والرسومات المتزنة.",
        },
    },
    {
        name: "ثلاثي الأبعاد (3D)",
        description: "إخراج مجسم يوحي بعمق واقعي وطبقات بصرية قوية، مناسب للقطع البارزة بصريًا.",
        sort_order: 110,
        metadata: {
            creative_direction: "dimensional 3d showcase",
            energy: "high",
            complexity: "bold",
            luxury_tier: "editorial",
            story_hook: "قطعة تبدو وكأن التصميم يخرج منها إلى الفراغ",
            keywords: ["3d", "render", "depth", "dimensional"],
            moods: ["مبهر", "تقني", "بارز"],
            audiences: ["editorial", "drops", "premium graphic lovers"],
            placements: ["chest", "back"],
            recommended_methods: ["from_text", "from_image", "studio"],
            notes: "يفضل للرموز المركزية والتكوينات الكبيرة ذات التأثير البصري.",
        },
    },
];

export const DTF_STUDIO_TECHNIQUE_CATALOG: DtfCreativeCatalogEntry[] = [
    {
        name: "رسم رقمي (Digital)",
        description: "إخراج رقمي نظيف وواضح يمنح حرية كاملة في الحدة والتفاصيل واللون.",
        sort_order: 10,
        metadata: {
            creative_direction: "clean digital execution",
            energy: "medium",
            complexity: "balanced",
            luxury_tier: "core",
            story_hook: "تنفيذ مرن وواضح يصلح لكل الأفكار تقريبًا",
            keywords: ["digital", "clean", "illustration", "sharp"],
            moods: ["مرن", "واضح", "حديث"],
            audiences: ["all", "daily luxury", "drops"],
            placements: ["chest", "back", "shoulder_right", "shoulder_left"],
            recommended_methods: ["from_text", "from_image", "studio"],
            notes: "الافتراضي الأكثر توازنًا حين لا توجد حاجة لملمس محدد.",
        },
    },
    {
        name: "ألوان مائية (Watercolor)",
        description: "طبقات شفافة ناعمة وتدرجات حالمة تناسب المشاهد الهادئة أو العضوية.",
        sort_order: 20,
        metadata: {
            creative_direction: "soft watercolor bloom",
            energy: "low",
            complexity: "balanced",
            luxury_tier: "signature",
            story_hook: "لوحة مطبوعة بخفة واتساع بصري غير صاخب",
            keywords: ["watercolor", "soft", "bleed", "organic"],
            moods: ["هادئ", "حالم", "ناعم"],
            audiences: ["gifts", "daily luxury", "feminine edits"],
            placements: ["chest", "back"],
            recommended_methods: ["from_text", "from_image", "studio"],
            notes: "ممتاز للزهور والطبيعة والرموز الهادئة والعناصر الشاعرية.",
        },
    },
    {
        name: "ألوان زيتية (Oil)",
        description: "ملمس عميق وضربات فرشاة واضحة، يعطي التصميم وزنًا فنيًا وحضورًا كلاسيكيًا.",
        sort_order: 30,
        metadata: {
            creative_direction: "rich oil texture",
            energy: "medium",
            complexity: "bold",
            luxury_tier: "editorial",
            story_hook: "يشبه لوحة فنية نقلت إلى القماش بدل أن تكون مجرد رسم رقمي",
            keywords: ["oil", "brushstroke", "texture", "fine art"],
            moods: ["عميق", "فني", "ثقيل"],
            audiences: ["editorial", "art lovers", "premium drops"],
            placements: ["chest", "back"],
            recommended_methods: ["from_text", "from_image", "studio"],
            notes: "يفضل للتكوينات الغنية والوجوه والعناصر ذات الثقل البصري.",
        },
    },
    {
        name: "رسم بالقلم (Pen)",
        description: "حبر وخطوط دقيقة وتظليل محكوم، مناسب للرسوم التفصيلية والأعمال المرسومة يدويًا.",
        sort_order: 40,
        metadata: {
            creative_direction: "pen sketch precision",
            energy: "medium",
            complexity: "balanced",
            luxury_tier: "signature",
            story_hook: "تصميم يبدو مرسومًا بعناية على دفتر فنان محترف",
            keywords: ["pen", "ink", "hatching", "sketch"],
            moods: ["دقيق", "فني", "مقروء"],
            audiences: ["illustration lovers", "daily luxury", "gifts"],
            placements: ["chest", "back"],
            recommended_methods: ["from_text", "from_image", "studio"],
            notes: "قوي في الخطوط، الخرائط البصرية، والرسوم الأحادية أو شبه الأحادية.",
        },
    },
    {
        name: "ايربراش (Airbrush)",
        description: "تدرجات ناعمة وهواء بصري لامع، مناسب للعناصر اللامعة والستايلات المعاصرة.",
        sort_order: 50,
        metadata: {
            creative_direction: "smooth airbrushed glow",
            energy: "medium",
            complexity: "balanced",
            luxury_tier: "editorial",
            story_hook: "نظرة مطبوعة بملمس لامع وانسيابي قريب من الملصقات المعاصرة",
            keywords: ["airbrush", "smooth", "glow", "gradient"],
            moods: ["لامع", "معاصر", "خفيف"],
            audiences: ["streetwear", "editorial", "drops"],
            placements: ["chest", "back"],
            recommended_methods: ["from_text", "from_image", "studio"],
            notes: "يفضل للأيقونات والوجوه والعناصر ذات الحضور الانسيابي.",
        },
    },
    {
        name: "حبر (Ink)",
        description: "تباين عالٍ وخطوط حاسمة ومساحات سوداء وبيضاء أنيقة، مناسب للطابع الدرامي.",
        sort_order: 60,
        metadata: {
            creative_direction: "high-contrast ink drama",
            energy: "medium",
            complexity: "balanced",
            luxury_tier: "signature",
            story_hook: "فخامة مشدودة بين الأبيض والأسود والضربة الحاسمة",
            keywords: ["ink", "contrast", "sumi-e", "dramatic"],
            moods: ["درامي", "حاسم", "راقي"],
            audiences: ["minimal luxury", "editorial", "calligraphy lovers"],
            placements: ["chest", "back", "shoulder_right"],
            recommended_methods: ["from_text", "from_image", "studio"],
            notes: "ممتاز للمخطوطات، الحيوانات، والتكوينات ذات التناقض الواضح.",
        },
    },
    {
        name: "طباعة ريزوغراف (Risograph)",
        description: "طابع مطبوع حبيبي وطبقات حبر متداخلة، مناسب للهوية الفنية والنوستالجيا المعاصرة.",
        sort_order: 70,
        metadata: {
            creative_direction: "riso print grain",
            energy: "medium",
            complexity: "balanced",
            luxury_tier: "core",
            story_hook: "قطعة تبدو كمطبوعة فنية قصيرة الإصدار",
            keywords: ["risograph", "grain", "print", "editorial"],
            moods: ["فني", "نوستالجي", "مطبوعي"],
            audiences: ["design lovers", "editorial", "drops"],
            placements: ["chest", "back"],
            recommended_methods: ["from_text", "from_image", "studio"],
            notes: "يناسب التكوينات الجرافيكية والطبقات اللونية المحدودة.",
        },
    },
];

export const DTF_STUDIO_PALETTE_CATALOG: DtfPaletteCatalogEntry[] = [
    {
        name: "تلقائي (Auto)",
        description: "اختيار لوني متزن يترك للنظام حرية مطابقة الفكرة بأفضل توزيع بصري.",
        sort_order: 10,
        colors: [
            { hex: "#111111", name: "Graphite" },
            { hex: "#F5F5F0", name: "Ivory" },
            { hex: "#C9A86A", name: "Warm Gold" },
        ],
        metadata: {
            palette_family: "adaptive premium",
            creative_direction: "balanced automatic palette",
            energy: "medium",
            complexity: "balanced",
            luxury_tier: "core",
            story_hook: "يترك القرار اللوني للنظام لكن داخل ذائقة محسوبة",
            keywords: ["auto", "adaptive", "balanced"],
            moods: ["متزن", "مرن", "عملي"],
            audiences: ["all"],
            placements: ["chest", "back"],
            recommended_methods: ["from_text", "from_image", "studio"],
            notes: "الخيار الافتراضي حين تريد أفضل توافق لوني تلقائيًا.",
        },
    },
    {
        name: "نيون ساطع (Neon)",
        description: "ألوان ضوئية حادة ولمعان حضري مناسب للتصاميم اللافتة.",
        sort_order: 20,
        colors: [
            { hex: "#00FFFF", name: "Cyan" },
            { hex: "#FF00FF", name: "Magenta" },
            { hex: "#00FF00", name: "Lime" },
        ],
        metadata: {
            palette_family: "neon contrast",
            creative_direction: "glowing neon signal",
            energy: "high",
            complexity: "bold",
            luxury_tier: "editorial",
            story_hook: "لوحة مشحونة كإضاءة مدينة ليلية",
            keywords: ["neon", "glow", "cyber", "contrast"],
            moods: ["متوهج", "حاد", "مستقبلي"],
            audiences: ["streetwear", "editorial", "drops"],
            placements: ["chest", "back"],
            recommended_methods: ["from_text", "from_image", "studio"],
            notes: "مثالية لستايل السايبر والهوية الحضرية المضيئة.",
        },
    },
    {
        name: "باستيل هادئ (Pastel)",
        description: "ألوان ناعمة وخفيفة تمنح التصميم هدوءًا بصريًا وأناقة لطيفة.",
        sort_order: 30,
        colors: [
            { hex: "#FFB6C1", name: "Pastel Pink" },
            { hex: "#ADD8E6", name: "Baby Blue" },
            { hex: "#98FB98", name: "Mint" },
        ],
        metadata: {
            palette_family: "soft pastel",
            creative_direction: "gentle pastel calm",
            energy: "low",
            complexity: "minimal",
            luxury_tier: "signature",
            story_hook: "مشهد لوني خفيف لا يزاحم الفكرة بل يحتضنها",
            keywords: ["pastel", "soft", "gentle", "airy"],
            moods: ["هادئ", "لطيف", "نظيف"],
            audiences: ["gifts", "daily luxury", "soft edits"],
            placements: ["chest", "back"],
            recommended_methods: ["from_text", "from_image", "studio"],
            notes: "مناسب للزهور، العناصر الناعمة، والمشاهد الحالمة.",
        },
    },
    {
        name: "أحادي اللون (Monochrome)",
        description: "اعتماد كامل على التدرج بين الأبيض والأسود، مثالي للفخامة الهادئة والوضوح.",
        sort_order: 40,
        colors: [
            { hex: "#FFFFFF", name: "White" },
            { hex: "#888888", name: "Gray" },
            { hex: "#000000", name: "Black" },
        ],
        metadata: {
            palette_family: "monochrome luxury",
            creative_direction: "black white editorial",
            energy: "low",
            complexity: "minimal",
            luxury_tier: "signature",
            story_hook: "قطعة قوية بلا ضوضاء لونية",
            keywords: ["mono", "black", "white", "editorial"],
            moods: ["راق", "حاسم", "نظيف"],
            audiences: ["minimal luxury", "editorial", "all"],
            placements: ["chest", "back", "shoulder_right"],
            recommended_methods: ["from_text", "from_image", "studio"],
            notes: "الأكثر أمانًا للطباعة الواضحة والهوية الكلاسيكية.",
        },
    },
    {
        name: "ألوان ترابية (Earth)",
        description: "درجات دافئة وطبيعية مستلهمة من الطين والخشب والزيتون والرمال.",
        sort_order: 50,
        colors: [
            { hex: "#8B4513", name: "Brown" },
            { hex: "#CD853F", name: "Terracotta" },
            { hex: "#556B2F", name: "Olive" },
        ],
        metadata: {
            palette_family: "earth warmth",
            creative_direction: "grounded earthy tone",
            energy: "medium",
            complexity: "balanced",
            luxury_tier: "signature",
            story_hook: "فخامة طبيعية دافئة وغير مصطنعة",
            keywords: ["earth", "olive", "terracotta", "natural"],
            moods: ["دافئ", "أصيل", "عضوي"],
            audiences: ["heritage lovers", "daily luxury", "gifts"],
            placements: ["chest", "back"],
            recommended_methods: ["from_text", "from_image", "studio"],
            notes: "ممتاز للموضوعات العضوية والهوية الهادئة القريبة من الطبيعة.",
        },
    },
    {
        name: "ريترو 80s (Retro)",
        description: "طيف لوني حار وجريء يستحضر ملصقات الثمانينات والهوية الرجعية.",
        sort_order: 60,
        colors: [
            { hex: "#FF69B4", name: "Hot Pink" },
            { hex: "#FF8C00", name: "Orange" },
            { hex: "#8A2BE2", name: "Purple" },
        ],
        metadata: {
            palette_family: "retro synth",
            creative_direction: "80s retro burst",
            energy: "high",
            complexity: "bold",
            luxury_tier: "core",
            story_hook: "طاقة نوستالجية واضحة مثل غلاف شريط قديم فاخر",
            keywords: ["retro", "80s", "nostalgia", "synth"],
            moods: ["مرِح", "صارخ", "نوستالجي"],
            audiences: ["drops", "streetwear", "retro fans"],
            placements: ["chest", "back"],
            recommended_methods: ["from_text", "from_image", "studio"],
            notes: "يناسب البوب آرت والأنمي والموضوعات الحيوية عالية الحضور.",
        },
    },
    {
        name: "فيبورويف (Vaporwave)",
        description: "لوحة حالمة بين الأزرق الوردي والبنفسجي، تمنح التصميم هوية مستقبلية شاعريّة.",
        sort_order: 70,
        colors: [
            { hex: "#00D4FF", name: "Turquoise" },
            { hex: "#FF00C1", name: "Pink" },
            { hex: "#9D00FF", name: "Purple" },
        ],
        metadata: {
            palette_family: "vaporwave dusk",
            creative_direction: "dreamy vapor horizon",
            energy: "high",
            complexity: "bold",
            luxury_tier: "editorial",
            story_hook: "لوحة كأنها غروب رقمي بين الحلم والمدينة",
            keywords: ["vaporwave", "dreamy", "sunset", "digital"],
            moods: ["حالم", "لامع", "غامر"],
            audiences: ["editorial", "drops", "cyber fans"],
            placements: ["chest", "back"],
            recommended_methods: ["from_text", "from_image", "studio"],
            notes: "ممتاز للسايبر، الأنمي، والمشاهد الخيالية ذات الإحساس الرقمي.",
        },
    },
];

export const DTF_STUDIO_CATALOG_COUNTS = {
    styles: DTF_STUDIO_STYLE_CATALOG.length,
    techniques: DTF_STUDIO_TECHNIQUE_CATALOG.length,
    palettes: DTF_STUDIO_PALETTE_CATALOG.length,
};
